#!/usr/bin/env python3

# Copyright (C) 2014 Science and Technology Facilities Council.
# Copyright (C) 2015-2026 East Asian Observatory.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

"""combine_cat: Generate combined catalog files from job output catalogs.

Usage:
    combine_cat --task=<task> (--out-base <base-file-name> | --list) [--peak | --extent] [--title=<title>]

Options:
    --task <task-name>           Task name
    --out-base <base-file-name>  Stem for output file names
    --list                       List catalog files instead of combining.
    --title <title>              Title for catalog name FITS header [default: Combined].
    --peak                       Only process "peak" catalogs.  (Currently only applies in non-list mode.)
    --extent                     Only process "extent" catalogs.  (Currently only applies in non-list mode.)
"""

from __future__ import absolute_import, division, print_function

import os.path

from astropy.io import fits
from docopt import docopt

from jsa_proc.admin.directories import get_output_dir
from jsa_proc.config import get_database
from jsa_proc.state import JSAProcState


def main():
    db = get_database()

    args = docopt(__doc__)

    process_peak = (args['--peak'] or not args['--extent'])
    process_extent = (args['--extent'] or not args['--peak'])

    if process_peak:
        peak = {'columns': None, 'data': [], 'nrows': 0}

    if process_extent:
        extent = {'columns': None, 'data': [], 'nrows': 0}

    if args['--list']:
        out_base = None
    else:
        out_base = args['--out-base']
        if not out_base:
            raise Exception('Output base file name must be specified')

    task = args['--task']
    states = JSAProcState.STATE_POST_RUN

    jobs = db.find_jobs(task=task, state=states, outputs='%-cat%.fits')

    n = 0.0
    n_jobs = float(len(jobs))

    for job in jobs:
        if out_base is not None:
            print('{:.1f}%'.format(100.0 * n / n_jobs), job.id, repr(job.outputs))
            n += 1.0

        # "find_jobs" doesn't normally return "state_prev" but we would need
        # to add it to distinguish jobs in the error state due to ingestion.
        # if ((job.state == JSAProcState.ERROR) and
        #         (job.state_prev != JSAProcState.INGESTING)):
        #     continue

        if job.outputs is None:
            continue

        for file in job.outputs:
            if '_peak-cat' in file:
                if process_peak:
                    product = peak

                else:
                    continue

            elif '_extent-cat' in file:
                if process_extent:
                    product = extent

                else:
                    continue

            else:
                raise Exception('Did not recognise file name: ' + file)

            pathname = os.path.join(get_output_dir(job.id), file)

            if out_base is None:
                print(pathname)

            else:
                with fits.open(pathname) as hdul:
                    table = hdul[1]

                    if product['columns'] is None:
                        product['columns'] = table.columns

                    elif product['columns'].names != table.columns.names:
                        raise Exception('Mismatch in columns in file: ' + file)

                    product['nrows'] += table.data.shape[0]
                    product['data'].append(table.data.copy())

    if out_base is not None:
        if process_peak:
            write_catalog(
                'peak', peak, out_base=out_base,
                tablename='{} peak catalog'.format(args['--title']))

        if process_extent:
            write_catalog(
                'extent', extent, out_base=out_base,
                tablename='{} extent catalog'.format(args['--title']))


def write_catalog(name, product, out_base, tablename):
    print('Preparing "{}" catalog'.format(name))
    ncols = len(product['columns'])
    print('Number of columns: {}'.format(ncols))
    print('Number of rows: {}'.format(product['nrows']))

    table = fits.BinTableHDU.from_columns(
        product['columns'], nrows=product['nrows'], fill=True)

    row = 0
    for data in product['data']:
        for i in range(0, data.shape[0]):
            for col in range(0, ncols):
                table.data[row][col] = data[i][col]

            row += 1

    table.header['EXTNAME'] = tablename

    hdul = fits.HDUList([
        fits.PrimaryHDU(),
        table,
    ])

    filename = '{}_{}-cat.fits'.format(out_base, name)
    print('Writing to file: {}'.format(filename))

    hdul.writeto(filename)


if __name__ == '__main__':
    main()
