#!/usr/bin/env python2

# Copyright (C) 2014 Science and Technology Facilities Council.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

from argparse import ArgumentParser
import logging
import sys

from jsa_proc.cadc.initial_import import import_from_cadcdp

parser = ArgumentParser()

parser.add_argument('--dry-run', '-n', required=False,
                    default=False, action='store_true')
parser.add_argument('--verbose', '-v', required=False,
                    default=False, action='store_true')

args = parser.parse_args()

logging.basicConfig(level=logging.DEBUG if args.verbose else logging.INFO)

if not import_from_cadcdp(dry_run=args.dry_run):
    sys.exit(1)
